import Head from "next/head";
import Header from "../components/header";
import Container from "../components/container";
import Footer from "../components/footer";
import Section from "../components/section";
import ShortAbout from "../components/home/about";
import ShortProjects from "../components/home/projects";
import SocialMedia from "../components/social-media";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Abhinandu V Nair</title> 
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header />

        {/* Landing Page Section */}
        <Section>
          <h1 className="text-3xl">Hi 👋,</h1>
          <h1 className="text-6xl font-bold my-6">
            I&apos;m{" "}
            <a
              className="text-indigo-600 dark:text-rose-400"
              href="https://abhndv.github.io/"
            >
              Abhinandu!
            </a>
          </h1>

          <p className="text-xl leading-relaxed max-w-[60%]">
            A passionate&nbsp;
            <code className="font-mono text-lg rounded bg-gray-100 p-1 dark:bg-gray-700">
              designer/developer
            </code>
            &nbsp; who loves to build solutions for both web and mobile. I
            occasionally design and improve experiences of applications. Haven't
            realised yet what suits me better Front End or Back End, so I build
            both.
          </p>
          <div className="my-6">
            <SocialMedia />
          </div>
        </Section>

        {/* About Me */}
        <ShortAbout />

        {/* Projects */}
        <ShortProjects />

        <Footer />
      </Container>
    </div>
  );
}
