import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Abhinandu V Nair</title> 
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hi 👋,</h1>
        <h1 className={styles.title}>
          I&apos;m <a href="https://abhndv.github.io/">Abhinandu V Nair!</a>
        </h1>

        <p className={styles.description}>
          A passionate <code className={styles.code}>designer/developer</code>
          who have hands on experience in creating for both web and mobile.
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with <a href="https://nextjs.org/">NextJS</a>
        </a>
      </footer>
    </div>
  );
}
