import Head from "next/head";
import Header from "../components/header";
import Container from "../components/container";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Abhinandu V Nair</title> 
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header />
        <main className="mt-48 ">
          <h1 className="text-3xl">Hi 👋,</h1>
          <h1 className="text-6xl font-bold my-6">
            I&apos;m{" "}
            <a className="" href="https://abhndv.github.io/">
              Abhinandu V Nair!
            </a>
          </h1>

          <p className="text-2xl leading-relaxed">
            A passionate&nbsp;
            <code className="font-mono text-xl bg-gray-100 p-1 dark:bg-gray-700">
              designer/developer
            </code>
            &nbsp; who has experience in creating both web and mobile.
          </p>
        </main>

        <Footer />
      </Container>
    </div>
  );
}
